### ISSUE TITLE
Integrate Sentry

### ISSUE THREAD

**Issue by abhishekgupta92** [navgurukul/galileo#101]
We have to integrate and verify that all the errors are being logged in Sentry. Sentry is an error logging application for which we have a paid subscription. We need to use it well to ensure that if there is any server-side error we can take a note of it, and fix it at the earliest.

**Comment by amarkrsinha1997** [comment]
What needs to be logged:
- API name.
- User Id.
- Date.

for the code base error.
- Line number.
- File.

for the user interaction error.
- log the payloads.
- log the response errors that are rejected.

**Comment by amarkrsinha1997** [comment]
Fixes
- [x] Sentry shouldn't be used in dev environment as it creates a problem to find bugs on Production.
- [x] Sentry is not showing any bug for prod environment.
- [x] Sentry is not working in the seed-courses check if it is working with seed-courses or not.

**Comment by amarkrsinha1997** [comment]
Reviewed and Tested.
