### ISSUE TITLE
Integrate GA

### ISSUE THREAD

**Issue by abhishekgupta92** [navgurukul/galileo#102]

**Comment by ajitAcc** [comment]
Hi @amarkrsinha1997 , this issue is addressed in kamaladevi at https://github.com/navgurukul/kamaladevi/issues/94
Nothing need to be done in Galileo side so close this issue.

**Comment by amarkrsinha1997** [comment]
Let me check with @abhishekgupta92  once

**Comment by amarkrsinha1997** [comment]
NEed to
