### ISSUE TITLE
Improve code to check user's role based on multiple roles available for that user.

### ISSUE THREAD

**Issue by ajitAcc** [navgurukul/galileo#105]
Improve/change code to check for user's role as below code will not work if user has multiple roles.

1. if (rows[0].roles !== 'admin') {
2. const isAdmin = rows[0].roles === 'admin' ? true : false;

Previously it work fine when user has only one role. But now as per current requirement one user can have multiple roles so this piece of code need to revisit and modified as per multiple roles. Need to change in all palace where above piece of code written.

**Comment by koushik-nodejs** [comment]
@abhishekgupta92  @amarkrsinha1997 :  we have completed the the changes and reviewed internally.
review from @amarkrsinha1997  is pending.

**Comment by amarkrsinha1997** [comment]
reviewed and tested.
