### ISSUE TITLE
meaningful error response message 

### ISSUE THREAD

**Issue by koushik-nodejs** [navgurukul/galileo#107]
Its related to issue #92

**Comment by koushik-nodejs** [comment]
In deleteMentorMenteeByidOrEmail() added different condition for checking the for different error  message:
1>except admin, facilitator or Tnp no one will be allowed to delete the record and corresponding error message.
2>then checking mentor exist or not and corresponding error message.
3>mentee exist or not and corresponding error message.
4>then mentee is belongs to that mentor or not
5>given mentor is real mentor of that mentee
6>user is allowed to delete record from that location.
7> last delete was successful or not

**Comment by koushik-nodejs** [comment]
@amarkrsinha1997  asked to change the message "The menteeId does not exist on the system" for invalid mentee and vise versa for mentor

**Comment by amarkrsinha1997** [comment]
Reviewed and Tested
