### ISSUE TITLE
Hi @amarkrsinha1997 following need to implement for search feature.

### ISSUE THREAD

**Issue by ajitAcc** [navgurukul/galileo#108]
Hi @amarkrsinha1997 Need new API for search Implement to get all course based on keyword entered  from davinci.courses where name like '%keyword%' 

_Originally posted by @ajitAcc in https://github.com/navgurukul/kamaladevi/issues/98#issuecomment-470840329_

**Comment by amarkrsinha1997** [comment]
We can implement the search filter in the front-end it-self will it be good or implementing it in backend would be good? as implementing the frontend with the same api seems easier as the we have to only filter the data which is coming from the backend what are your thought?
@ajitAcc

**Comment by ajitAcc** [comment]
Hi @amarkrsinha1997 , as discussed in call. 
1. Search will be as given in this link for reference.
    https://ahfarmer.github.io/emoji-search/
2. Search will be done from all courses which were displayed on home page.
3. No API call for this features as search will be done only from available display courses. hence closing this issue.
