### ISSUE TITLE
Access Control for getting course relation

### ISSUE THREAD

**Issue by amarkrsinha1997** [navgurukul/galileo#115]
the getCourseRelationList controller should have access control limited to Admin, T&P, Facilitator

**Comment by koushik-nodejs** [comment]
Please update the requirement as discussed for adding access for facilitator and tnp  --- @amarkrsinha1997

**Comment by amarkrsinha1997** [comment]
> Please update the requirement as discussed for adding access for facilitator and tnp --- @amarkrsinha1997

Done
