### ISSUE TITLE
Course Seeder - Change location of info.md file

### ISSUE THREAD

**Issue by abhishekgupta92** [navgurukul/galileo#131]
Currently, the course information is fetched from 

```details/info.md```

We can get rid of the ```details``` folder and simply have ```info.md``` file in the main folder. The course update scripts need to be updated accordingly.

Check this file for example - https://github.com/navgurukul/newton/blob/master/3000words/details/info.md

You also need to look at 
https://github.com/navgurukul/galileo/blob/master/src/seed-courses

Please be conscious of the fact that we shouldn't break the existing code. 

Before you attempt the task, please reply with a sub-task list.
After you have completed the task, please create a PR for @abhishekgupta92 to review.

**Comment by prince1837** [comment]
I not getting `details/info.md` This file in galileo repository

**Comment by abhishekgupta92** [comment]
No this file is in course content.
Checkout Newton repository

**Comment by Rohit1999-dev** [comment]
I understand the things which I have to do. Firstly, I have to configure the whole courses of Newton Project According to instructions of readme.md file of Galileo.

**Comment by prince1837** [comment]
@abhishekgupta92 what is the role of notes.md?
Do we also have to put notes.md in courses file like info.md?

**Comment by abhishekgupta92** [comment]
No, there's another issue which asks for it to be removed from curriculum
and codebase

**Comment by Rohit1999-dev** [comment]
- [x] Firstly, We understand the things from where code blog is controlling all the courses.

- [x]  Second thing, we have to move the location of info.md file from details files.
