### ISSUE TITLE
Not needed - the functionality of notes

### ISSUE THREAD

**Issue by abhishekgupta92** [navgurukul/galileo#39]
GET /courses/{courseId}/notes

Remove the functionality and corresponding database fields.

Check this file for example - https://github.com/navgurukul/newton/blob/master/3000words/details/notes.md

You also need to look at 
https://github.com/navgurukul/galileo/blob/master/src/seed-courses

**Comment by amarkrsinha1997** [comment]
Do we still need to do these issues or shall we wait if this feature would be required in the future? @abhishekgupta92

**Comment by Rohit1999-dev** [comment]
I understand that things, firstly I have to remove that table(notes) from databases.
