### ISSUE TITLE
Issues faced while installing

### ISSUE THREAD

**Issue by esitharth** [navgurukul/galileo#41]
**> gulp build** 
'tslint' errored after 3.1 s
[15:02:35] Error in plugin 'gulp-tslint'
Message:
    Failed to lint: seed-courses.ts[103, 1]: if statements must be braced, seed-courses.ts[104, 1]: if statements must be braced, seed-courses.ts[105, 1]: if statements must be braced, seed-courses.ts[106, 1]: if statements must be braced, seed-courses.ts[10, 35]: Missing semicolon, seed-courses.ts[103, 10]: == should be ===, seed-courses.ts[104, 10]: == should be ===, seed-courses.ts[105, 10]: == should be ===, seed-courses.ts[106, 10]: == should be ===, seed-courses.ts[106, 27]: == should be ===, seed-courses.ts[106, 44]: == should be ===, controllers/courses/course-controller.ts[165, 43]: Missing radix parameter, controllers/courses/course-controller.ts[177, 39]: Missing radix parameter.
node_modules/@types/node/index.d.ts(217,5): error TS2403: Subsequent variable declarations must have the same type.  Variable 'resolve' must be of type 'string', but here has type 'RequireResolve'.
node_modules/@types/node/index.d.ts(219,5): error TS2403: Subsequent variable declarations must have the same type.  Variable 'extensions' must be of type 'any', but here has type 'NodeExtensions'.
..........................
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! typescript-node@1.0.0 tsc: `tsc`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the typescript-node@1.0.0 tsc script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/dexter/.npm/_logs/2018-08-09T09_32_37_981Z-debug.log
[15:02:38] 'compile' errored after 5.27 s
[15:02:38] Error: Command `npm run tsc` failed with exit code 2
    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)

**> gulp tslint**
Error in plugin 'gulp-tslint'
Message:
    Failed to lint: seed-courses.ts[103, 1]: if statements must be braced, seed-courses.ts[104, 1]: if statements must be braced, seed-courses.ts[105, 1]: if statements must be braced, seed-courses.ts[106, 1]: if statements must be braced, seed-courses.ts[10, 35]: Missing semicolon, seed-courses.ts[103, 10]: == should be ===, seed-courses.ts[104, 10]: == should be ===, seed-courses.ts[105, 10]: == should be ===, seed-courses.ts[106, 10]: == should be ===, seed-courses.ts[106, 27]: == should be ===, seed-courses.ts[106, 44]: == should be ===, controllers/courses/course-controller.ts[165, 43]: Missing radix parameter, controllers/courses/course-controller.ts[177, 39]: Missing radix parameter.

**>npm run start**
Check GALILEO_ENV variable

**Comment by abhishekgupta92** [comment]
export GALILEO_ENV='local'
and ensure conflg.local.json exists in the configurations folder
