### ISSUE TITLE
GET /courses has a problem without authenticaiton

### ISSUE THREAD

**Issue by RishabhVerma** [navgurukul/galileo#52]
When I make an un-authenticated request on `/courses` it only returns 3 courses. While an authenticated request returns all the courses available.

The response for an un-authenticated request is this.
```json
{
"availableCourses": [
{
"id": 42,
"name": "Samvaad - Learning through dialogue!",
"type": "html",
"logo": "http://Google.com",
"shortDescription": "Learn English with one-on-one dialogues and reflecting on various important topics"
},
{
"id": 43,
"name": "NavGurukul Learning Framework",
"type": "js",
"logo": "http://google.com/logo.png",
"shortDescription": "Understanding framework of how NavGurukul Works"
},
{
"id": 44,
"name": "Manthan",
"type": "html",
"logo": "http://google.com/logo.png",
"shortDescription": "Manthan Opportunities and Experiences"
}
]
}
```

When an unauthenticated request is made, all the courses in the NG universe should be returned.

**Comment by amarkrsinha1997** [comment]
running it in my localhost send every course and can't find any such problem of authentication

**Comment by RishabhVerma** [comment]
@amarkrsinha1997 This is not working properly. Go to http://saral.navgurukul.org/api/courses to check it out.

**Comment by RishabhVerma** [comment]
@amarkrsinha1997 Did you check this out?

**Comment by amarkrsinha1997** [comment]
yes
