### ISSUE TITLE
sequenceNum for courses

### ISSUE THREAD

**Issue by abhishekgupta92** [navgurukul/galileo#65]
create a sequenceNum variable for courses to determine their order in the main page.

in the course listing page the sequenceNum will be used in order by field. make appropriate changes in all those listings. 

create an admin role and add me, you and rishabh to it. 

let admins change the sequence order of the course

**Comment by amarkrsinha1997** [comment]
1. Creating a sequenceNum variable in Mysql which will initially be in increasing order but the admins can change its order from the front-end. 
2. Create a route which will be called with all courseIDs and new SequenceNum variable to update the sequence of each number.
3. Creating a specific controller and schema also for updatingSequnceNum of courses
4. Send the SequenceNum variable from getCoursesList routes.
5. Updating controller-schema-routes for getCourseList.

**Comment by amarkrsinha1997** [comment]
@abhishekgupta92

**Comment by amarkrsinha1997** [comment]
```mysql 
CREATE TABLE `user_roles` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `userId` int(11) unsigned DEFAULT NULL UNIQUE,
  `roles` enum('students','facilitators','admin') DEFAULT 'students',
  PRIMARY KEY (`id`),
  KEY `user_role_ibfk_1_idx` (`userId`),
  CONSTRAINT `user_roles_ibfk_1` FOREIGN KEY (`userId`) REFERENCES `users` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```

```mysql
ALTER TABLE courses ADD COLUMN sequenceNum INT;
```
