### ISSUE TITLE
Course Dependency System.

### ISSUE THREAD

**Issue by amarkrsinha1997** [navgurukul/galileo#73]
There should be a courses dependency system so that a student knows the track of there studying and can follow it sequence wise and doesn't get distracted with so many courses around.

The courses dependency system will work such as only those courses would be shown to the students for which all the dependency courses have been completed or there are no dependency courses.

Once the student has completed at least 70% of the dependency courses for any course, the course should automatically get unlocked along with an email to the user notifying about the course unlocking and be available for enrolment by the student.

## Part I
1. Create a table courseRelation with columns
`courseId`
`reliesOn`

2. Update Schema.sql

3. Create endpoints to add a course relation or remove a course relation

4. Create an endpoint to give a list of all courses with their dependencies

## Part II
1. Changes /courses route:

a. A student can only see the courses which are open for them currently (The courses which don't have any dependency or which all dependency has been completed at least 70%) 

b, 70% should be a parameter that can be configured from config.dev/prod.json

## Part III

a. create a function which takes user id, and course id and returns if the student can enroll in a course or not

b. use this function to change the /enroll endpoint

c. use this function to disallow users to submit assignment when the user isn't enroled

## Part IV

When a user's assignment is successfully approved then, check if any dependency course is unlocked. If yes, send an email to the user.

**Comment by abhishekgupta92** [comment]
Please do this at the earliest. Really crucial and urgent features.

**Comment by ANAKALAASHOK** [comment]
@amarkrsinha1997 , in part-1 task, which adding or removing any course dependency with course id and relieson, is that admins only can add or delete the course dependency?

**Comment by ANAKALAASHOK** [comment]
@amarkrsinha1997 , in Part -2 task, how are we going to calculate completion of 70% course dependency

**Comment by amarkrsinha1997** [comment]
@ANAKALAASHOK  
For now we can go with Admin can only create course dependency.

Formula total submission by the student  for   the course / total exercises  in the course which doesn't  have submissionType null

**Comment by amarkrsinha1997** [comment]
```mysql 
COUNT(CASE WHEN exercises.submissionType IS NOT NULL THEN 1 END) as totalExercises
COUNT(DISTINCT submissions.id) as completedSubmissions
```
this might help you to count it

**Comment by abhishekgupta92** [comment]
@ANAKALAASHOK - Can you let me know if you need any help with the task. Looking forward :-)

**Comment by Rajat2008** [comment]
The solution for part 1 has been implemented :-
Three endpoints have been created for each of the operations mentioned in Part1.

1.  'getCourseRelationList' function in course-controller gives a list of all courses with their dependencies. The route for this is '/courseRelation.'

2.'deleteCourseRelation' function in course-controller removes a course relation. The corresponding route for this is '/courseRelation/{courseId}/{reliesOn}/delete',

3.'addCourseRelation' function in course-controller adds a new course relation. The corresponding route for this is '/courseRelation/{userId}/{courseId}/{reliesOn}/add'.

schema.sql has also been updated with the changes for 'courseRelation' table.

**Comment by Rajat2008** [comment]
In task 2, 70% exercises of all the exercises should be completed or the exercises for each of the dependent courses should be individually completed by 70%.  Below are the two different scenarios -

Case 1 - 
Suppose course 'C1' is dependent on 3 differenet courses A,B,C.
The completion status for each one of them is-
A - 80%
B-  60%
C - 70%
The average taken of the three courses is = 80+70+60/3 = 70%.

Case 2 - 
Suppose course 'C2' is dependent on three different courses X,Y,Z.
The completion status for each one of them is-
X - 70%
Y - 70%
Z - 70%
Here each of the courses is individually complete by 70%.

Hi @amarkrsinha1997 , @abhishekgupta92  ,Which of the above two cases is/are eligible to be unlocked(whether C2 or both of them).

**Comment by abhishekgupta92** [comment]
C2 @Rajat2008

**Comment by ANAKALAASHOK** [comment]
@abhishekgupta92 @amarkrsinha1997 , In task 2, how can we submit the exercise for a particular course from the front end part such that record should be inserted in the submission table in database?

**Comment by ANAKALAASHOK** [comment]
@amarkrsinha1997 @abhishekgupta92 , In task 3, 
1. if a student has enrolled any course, what will be the value inserted in the enrolled column, 
    if not what will be the value in enrolled column in course_enrollment table.
	
2.  In which endpoint need to update the created function, to disallow users to submit assignment when the user isn't enrolled.

**Comment by abhishekgupta92** [comment]
> @abhishekgupta92 @amarkrsinha1997 , In task 2, how can we submit the exercise for a particular course from the front end part such that record should be inserted in the submission table in database?

Hi @ANAKALAASHOK, I didn't understand this part. Can you call me for this? My number is nine nine five eight 0 0 thirty two fourty two

**Comment by abhishekgupta92** [comment]
> 1. if a student has enrolled any course, what will be the value inserted in the enrolled column,
>    if not what will be the value in enrolled column in course_enrollment table.

this is the table structure

![capture](https://user-images.githubusercontent.com/1681009/51301501-7771cd80-1a55-11e9-8b13-e8496e0440bf.PNG)

courseStatus will be enroll in that case

**Comment by abhishekgupta92** [comment]
> 2\. In which endpoint need to update the created function, to disallow users to submit assignment when the user isn't enrolled.

`postExerciseSubmission` in `src/controllers/assignments/assignment-controller.ts`

**Comment by Rajat2008** [comment]
The solution for part2 has been implemented. The changes have been done in the course-controller and course-helper files. In the course-controller file, the logic in the getCoursesList function has been updated to filter the results according to the completion criteria that can be configured through config file.

A new function named 'manipulateResultSet' has been added to the course-helper file to perform the necessary data manipulaltions.

**Comment by Rajat2008** [comment]
Hi @abhishekgupta92 , @amarkrsinha1997 ,
For part III a.) ,What is the condition(functionally) to decide whether a user can enroll in a given course or not.

**Comment by abhishekgupta92** [comment]
As discussed, condition as same as that of when the student can see a course or not.
This is just an additional backend check.

Also, what's the ETA for this issue?

**Comment by Rajat2008** [comment]
hi @amarkrsinha1997 , As discussed please provide me the correct version of 'editPeerReview' function in assignment-controller . so that I can conclude the work of part 4.

**Comment by amarkrsinha1997** [comment]
> hi @amarkrsinha1997 , As discussed please provide me the correct version of 'editPeerReview' function in assignment-controller . so that I can conclude the work of part 4.

Sorry I didn't get what you want? @Rajat2008

**Comment by amarkrsinha1997** [comment]
@abhishekgupta92 Please update the config.prod.json new changes there.
Reviewed and Tested:
- Part 1
- Part 2
- Part 3

**Comment by amarkrsinha1997** [comment]
reviewed and closed
