### ISSUE TITLE
Solution for a problem statement - Seeding Scripts and API

### ISSUE THREAD

**Issue by abhishekgupta92** [navgurukul/galileo#87]
Modify the `seed-courses` module in the `src` folder, such that we can now import solutions of an exercise. 

Example file is 
https://github.com/navgurukul/newton/blob/master/hangman/available-letters.md

Currently, the solution is posted in the file itself, because of which it is directly displayed in the course content view itself.

However, the new structure is as follows

`index.md` would be modified to say:

- available-letters.md
   - available-letters-solution.md

If there is a fileName with an indentation to the right of a `.md` the file then the file will be assumed to be the solution and will be inserted `solution` in the database along with the exercise content. 

## Part 2
Create an API that takes in the exerciseId and returns the solution content in markdown format.

## Part 3
Modify the course content API to return a boolean parameter ifSolution

**Comment by Rajat2008** [comment]
@abhishekgupta92 , @amarkrsinha1997 - Please suggest a naming convention, that will be used for naming the solution files. It is required to identify a solution file.

**Comment by amarkrsinha1997** [comment]
Hey @Rajat2008, I talked with Abhishek on this, copy pasting the message right here:
there is a fileName with an indentation to the right of a .md the file then the file will be assumed to be the solution and will be inserted solution in the database along with the exercise content, irrespective of the name.

**Comment by Rajat2008** [comment]
The solution for part 3 has been implemented.
Please find below, details of the solution implemented. 
2.	Created a function ‘getIsSolutionAvailable’ in the new helper file ‘courseHelper.ts’ to check whether a solution exists.
3.	Returned the boolean ‘ifSolution’ based on the value returned by ‘getIsSolutionAvailable’.

**Comment by Rajat2008** [comment]
The solution for Part1 has been implemented.
Please find below. details of the solution implenented.
1.Altered the logic in the 'getSequenceNumbers' function of the helpers.ts file to generate the correct sequence numbers , according to the new structure of the 'info.md' file. Also written the logic to identify a solution file and attached a boolean flag named 'isSoltuionFile' accordingly. 

2. Updated the 'addOrUpdateExercises' function in the database,ts file to match an exercise file with the solution file and add the contents of the solution file to solution column in the table.

**Comment by Rajat2008** [comment]
The solution for Part2 is as follows:-
1.Created a new function 'getSolutionByExerciseId' in the course-controller.ts that returns the solution of an exercise based on the exerciseId.

**Comment by Rajat2008** [comment]
I have committed the code for this issue in the accenture-test branch.

**Comment by amarkrsinha1997** [comment]
@Rajat2008 cool can you create a pull request to master once you have tested your code?
with the SQL queries written there?

**Comment by abhishekgupta92** [comment]
@Rajat2008 - Let me know whenever you have done, we will merge this and create a new issue for you to work on. Thanks.

**Comment by Rajat2008** [comment]
Hi @abhishekgupta92 , @amarkrsinha1997 , I am not able to push the  code, getting error -

**remote: Permission to navgurukul/galileo.git denied to Rajat2008.**.Please provide me write access to branch 'accenture-test'.

**Comment by Rajat2008** [comment]
> @Rajat2008 cool can you create a pull request to master once you have tested your code?
> with the SQL queries written there?

Hi @amarkrsinha1997 , @abhishekgupta92 . could you please confirm. Which are the sql queries that you are referring to for testing.?

**Comment by Rajat2008** [comment]
> Hi @abhishekgupta92 , @amarkrsinha1997 , I am not able to push the code, getting error -
> 
> **remote: Permission to navgurukul/galileo.git denied to Rajat2008.**.Please provide me write access to branch 'accenture-test'.

The access issue has been resolved, able to push the code now.

**Comment by Rajat2008** [comment]
> > Hi @abhishekgupta92 , @amarkrsinha1997 , I am not able to push the code, getting error -
> > **remote: Permission to navgurukul/galileo.git denied to Rajat2008.**.Please provide me write access to branch 'accenture-test'.
> 
> The access issue has been resolved, able to push the code now.
