### ISSUE TITLE
Peer Review - Basic Reporting

### ISSUE THREAD

**Issue by abhishekgupta92** [navgurukul/galileo#91]
## Access Control
- Only for Admins

## Parameter
Center Wise Reports (Dharamsala, Bangalore, All)

### API 1
- Number of pending `review requests`
- Number of review requests created
---- Today
---- Yesterday
---- Last Week
---- Last Month

### API2
- Requests pending for (user, count) array

## Email
Send above report daily to platform+reports@navgurukul.org using above APIs/functions. A frontend dashboard using the above API will be made soon.

**Comment by Rajat2008** [comment]
Need to have an access check - Only Admins should be able to do this

API 1:-
The API should take on input parameter(Center)
the input values for the center could be(Dharamsala, Bangalore, All).

The return value of the API1 should be - 

```js
{
  "numberOfPendingRequests": 12,
  "numberOfRequestCreated": {
    "requestTodays": 1, 
    "requestYesterday": 2, 
    "requestLastWeek": 19,  
    "requestLastMonth": 30,
  }
}
```

**Comment by Rajat2008** [comment]
The access control should be in place for API 2 as well -
The center field is required(Dharamsala, Bangalore, All);
the Requests that are pending for users-
```js
[
  {name:"username1", numberOfAssignmentSubmitted: 20, numberOfAssignmentToReview: 30},
  {name:"username2", numberOfAssignmentSubmitted:23, numberOfAssignmentToReview: 30}
]
```
For now, let's go as the assignments that the users have been assigned as numberOfPendingRequest.
I will ask Abhishek for the double check for it as do we require the assignments that user have submitted or the assignment the user has been assigned to be count

**Comment by amarkrsinha1997** [comment]
Email:
`Send above report daily to platform+reports@navgurukul.org using above APIs/functions.`
Use a script that is being run daily at a certain time.
time and email should configurable in config.dev/prod.json
and for now, use cron job to do this work make a bash file that sets the cronjob to do the work.

**Comment by ajitAcc** [comment]
Hi @abhishekgupta92 @amarkrsinha1997 Please find attached document for issue with one user having  multiple roles with different locations.   
[Issues related with multiple roles in users.docx](https://github.com/navgurukul/galileo/files/2945475/Issues.related.with.multiple.roles.in.users.docx)

**Comment by amarkrsinha1997** [comment]
- There is no need of numberOfAssignmentToReview, Here we only have to count the numberOfAssignmentSubmitted 
confirm from Abhishek.


- Count only students in a center assignment submitted request

- Shift the student center from users table to user_roles table

**Comment by Rajat2008** [comment]
Hi,
As discussed, @amarkrsinha1997 
1.We will use center from the users table.
2,The students that do not have any center will not be a part of these reports.

**Comment by koushik-nodejs** [comment]
@amarkrsinha1997  we taking this as a consideration as of now that user after registering to the system he can not change his center.

**Comment by amarkrsinha1997** [comment]
API 2 Reviewed needs Testing

**Comment by amarkrsinha1997** [comment]
Done and reviewed need the constant value's to be added in sample-config.json

**Comment by amarkrsinha1997** [comment]
reviewed and tested
