### ISSUE TITLE
APIs to manage mentors

### ISSUE THREAD

**Issue by abhishekgupta92** [navgurukul/galileo#92]
### Access control
`tnp`, `facilitator` and `admins`

### API 1
For a center (paramenter)
- return the list of students without mentors

### API 2
For a center (parameter)
- return the list of mentees and mentors

### API 3
For a mentor (id) and mentee (id) (parameters)
- create an api to delete that row from the table

### API 4
For a mentor (email or id) and mentee (id) (parameters)
- create an api to delete that row from the table

### API 5
For a center (parameter)
- return the list of all the students in that mentor

**Comment by koushik-nodejs** [comment]
@amarkrsinha1997 & @abhishekgupta92 for API 3 : 
There 4 scenarios may arise : 
1> Mentor id provided as an argument which does not exist but MenteeId exist in the table.
2> Mentee id provided as an argument which does not exist but MentorId exist in the table itself.
3> Mentor and Mentee id both are not exist in the table.
4> where Mentor and Mentee Id exist but not in the same row , exist in different row combination .

 So for those above points can you plz share the different error messages.

**Comment by koushik-nodejs** [comment]
@abhishekgupta92  & @amarkrsinha1997 - need clarification on access control : do I need to implement all the access control for get type of request also? and what will be the case for delete scenario .

**Comment by koushik-nodejs** [comment]
@amarkrsinha1997 - for API no 2:
As discussed in the call that mentor and mentee will be listed in a tree structure , where some one will be the parent mentor and under him some student will be there and those student can be a mentor for others  like a tree.
so here for one scenario we need a clarification that -
scenario1 : suppose there student A is mentor for student B & C.
                  **is there any possibilities that student B also can be a mentor for student A?** 
@abhishekgupta92

**Comment by amarkrsinha1997** [comment]
> @amarkrsinha1997 & @abhishekgupta92 for API 3 :
> There 4 scenarios may arise :
> 1> Mentor id provided as an argument which does not exist but MenteeId exists in the table.
> 2> Mentee id provided as an argument which does not exist but MentorId exists in the table itself.
> 3> Mentor and Mentee id both do not exist in the table.
> 4> where Mentor and Mentee Id exist but not in the same row, exist in different row combination.
> 
> So for those above points can you plz share the different error messages.

1. The mentorId is not a mentor.
2. The menteeId doesn't have any mentor.
3. MentorId and menteeId both doesn't exist in the platform.
4. The mentorId <id> is not the mentor of the menteeId <id>.

**Comment by amarkrsinha1997** [comment]
> @amarkrsinha1997 - for API no 2:
> As discussed in the call that mentor and mentee will be listed in a tree structure , where some one will be the parent mentor and under him some student will be there and those student can be a mentor for others like a tree.
> so here for one scenario we need a clarification that -
> scenario1 : suppose there student A is mentor for student B & C.
> **is there any possibilities that student B also can be a mentor for student A?**
> @abhishekgupta92

No at a time only A can be the mentor of B & C.
and there would be only 1 mentor assigned to a mentee.

**Comment by amarkrsinha1997** [comment]
> @abhishekgupta92 & @amarkrsinha1997 - need clarification on access control: do I need to implement all the access control forget type of request also? and what will be the case for delete scenario?

Yes only the roles above are allowed to access, you might need to create tnp roles in user_roles table

**Comment by Rajat2008** [comment]
Hi @abhishekgupta92 , @amarkrsinha1997, 
Please provide access to Ajit and Koushik for code push in Galileo. The user Id and email Ids are as follows -
1. Koushik-nodejs (koushik.santra@acccenture.com)
2, ajitAcc (ajit.sinh417@gmail.com)

**Comment by koushik-nodejs** [comment]
> > @abhishekgupta92 & @amarkrsinha1997 - need clarification on access control: do I need to implement all the access control forget type of request also? and what will be the case for delete scenario?
> 
> Yes only the roles above are allowed to access, you might need to create tnp roles in user_roles table

for all center or center specific , means any facilitator from any center is allowed to do this activity ?

**Comment by koushik-nodejs** [comment]
@abhishekgupta92 @abhishekgupta92  development , review  completed merging is pending .

**Comment by amarkrsinha1997** [comment]
Facilitator, TNP, and admin should be either from the same center or for all centers.

**Comment by amarkrsinha1997** [comment]
Reviewed and Done.
