### ISSUE TITLE
Notification System using Cliq

### ISSUE THREAD

**Issue by abhishekgupta92** [navgurukul/galileo#97]
Cliq powered by Zoho is the official communication client used by navGurukul. Students check it more frequently than they even do their emails.

We need to integrate the backend with Cliq, such that a notification system is built which alert users about the various notifications. 

## Some Important Use Cases

- You have received a new peer review request.
- Your assignment has been reviewed and approved.
- Your assignment has been reviewed and rejected.
- A new course dependency is unlocked.
- A course I am enrolled in is marked completed.
- Changes have been made in a course that I am enrolled in.
    - New Concepts Added
    - Change in concepts
    - Don't cover deletion in concepts
- A new course has been added.

The messages will be sent by a normal Cliq user account. We have worked extensively on Cliq, and we will help with the endpoint that needs to be called from the server whenever a user is to be notified.

**Comment by koushik-nodejs** [comment]
Need clarification no few point :
1> "The messages will be sent by a normal Cliq user account. "--- what type of message is going to sent to use? is it a campaign message ?

2>"Students check it more frequently than they even do their emails."----all user account is connected with zoho ?
3>"We need to integrate the backend with Cliq, such that a notification system is built which alert users about the various notifications."-- user is going to check it in zoho dashboard ?
@amarkrsinha1997

**Comment by amarkrsinha1997** [comment]
Hey Ajit,

Thanks for the questions.
We currently use Cliq as our online communication software and all the
students are actively using it to do the communication within the
organization.
1. The message would be the notification for the students like they have a
new course to be open when they have completed the 70% criteria.
2. Yes
3. Can you create a function which takes an email and a message to be sent
to the Cliq user by finding them using email on Cliq?

Thanks & Regards
Amar Sinha

**Comment by amarkrsinha1997** [comment]
Task For Me:
- Get API & token from Abhishek.
- Add one of Accenture team on Cliq.

**Comment by amarkrsinha1997** [comment]
Who will be sending the message a bot or something

**Comment by amarkrsinha1997** [comment]
https://www.zoho.com/cliq/help/restapi/v2/#authentication

**Comment by koushik-nodejs** [comment]
> https://www.zoho.com/cliq/help/restapi/v2/#authentication

what will be the authtoken?

**Comment by amarkrsinha1997** [comment]
I will be sending that in mail.

**Comment by koushik-nodejs** [comment]
Need to add my email [dev.koushiksantra@gmail.com, koushik.santra@accenture.com] to navgurukul zoho account ..-- @amarkrsinha1997

**Comment by koushik-nodejs** [comment]
From now for those above functionality  for intimation it will not use email , it will use Cliq message system- By @amarkrsinha1997

**Comment by koushik-nodejs** [comment]
@amarkrsinha1997 -  please provide message text for those above condition

**Comment by koushik-nodejs** [comment]
-- @amarkrsinha1997 , Please suggest
 in which of the following two scenarios a course would be considered as 'Completed'?--
1> After all the exercise in a course have been completed .
2> After the mentor of a course marks it as 'Completed'

**Comment by koushik-nodejs** [comment]
> * Changes have been made in a course that I am enrolled in.

--- do we also need to notify the students who has already completed the course 
   if yes do we need to keep a check on how many months it has been science they have completed the course.
Exmp:- 
1> I have completed python course a month ago and now there is a new changes, which I need to know.
2> I have completed python course 6th months ago  and now there is a new changes, which is really basic for me , and i am playing with advance python.
@amarkrsinha1997

**Comment by amarkrsinha1997** [comment]
> -- @amarkrsinha1997 , Please suggest
> in which of the following two scenarios a course would be considered as 'Completed'?--
> 1> After all the exercise in a course have been completed .
> 2> After the mentor of a course marks it as 'Completed'

both

**Comment by amarkrsinha1997** [comment]
> > * Changes have been made in a course that I am enrolled in.
> 
> --- do we also need to notify the students who has already completed the course
> if yes do we need to keep a check on how many months it has been science they have completed the course.
> Exmp:-
> 1> I have completed python course a month ago and now there is a new changes, which I need to know.
> 2> I have completed python course 6th months ago and now there is a new changes, which is really basic for me , and i am playing with advance python.
> @amarkrsinha1997

send the cliq notification to all those who are enrolled and if someone doesn't want the notification then they can unenroll from the course

**Comment by amarkrsinha1997** [comment]
Create cliqMessages.js within configuration file which will contain different functions to get string required to send the student. 
suppose if I have to send assignment submission.

I function would be there name as assignmentSubmissionMessage & assignmentReviewMessage
which will take the name of the student & the link to the assignment review.

**Comment by amarkrsinha1997** [comment]
> Cliq powered by Zoho is the official communication client used by navGurukul. Students check it more frequently than they even do their emails.
> 
> We need to integrate the backend with Cliq, such that a notification system is built which alert users about the various notifications.
> 
> ## Some Important Use Cases
> * You have received a new peer review request.
> * Your assignment has been reviewed and approved.
> * Your assignment has been reviewed and rejected.
> * A new course dependency is unlocked.
> * A course I am enrolled in is marked completed.
> * Changes have been made in a course that I am enrolled in.
>   
>   * New Concepts Added
>   * Change in concepts
>   * Don't cover deletion in concepts
> * A new course has been added.
> 
> The messages will be sent by a normal Cliq user account. We have worked extensively on Cliq, and we will help with the endpoint that needs to be called from the server whenever a user is to be notified.

*  Hi (Reviewer) apke pass (submitter) ka assignment aya hai app ishe yahan review karwasakte hai.

* Hi (Submitter) apka assignment (reviewer) ne approve kardiya ha app ushe yahan dekh sakte ho 
   - http://saral.navgurukul.org/course?id=(courseId)&slug=(exercieseSlug) 

* Hi (Submitter) apka assignment (reviewer) ne reject kardiya ha app unke diye gaye feedback par kaam karke phirse assignment submit  karsakte ho
  - Apke assignment ka link
  - http://saral.navgurukul.org/course?id=(courseId)&slug=(exercieseSlug) 

* Congrats, Apne yeh course (percent) complete karlia hai isliye apke liye 3 naye courses unlock hogye
  - Course 1 (Url - http://saral.navgurukul.org/course?id=<courseId>)
  - course 2 - (course url)

* Congrats, Apka course (courseName) apke mentor (mentor) ne complete mark kardiya ab aap aage ke courses karsakte hai.

* Hi (student), 
  - (courseName) course me kuch naye topic add hue hai aap ushe yahan click karke dekh sakte ha.
     - Exercise Name-Exercise Url
     - Exercise Name-Exercise Url

   - Aur kuch purane topics me changes hue hai joh niche diye gaye hai.
     - Exercise Name Exercise Url
     - Exercise Name Exercise Url


* Hi (student), humne SARAL pe naye courses launch kia inh courses ko niche diye gaye link pe click karke dekh sakte ho.
  - courseName course url
  - courseName course url


@koushik-nodejs this is the message for the Cliq Notification & sorry for the delay's

**Comment by koushik-nodejs** [comment]
A course I am enrolled in is marked completed. ---
for this when a course automatically get completed after completing all exercise associated with course then what will be the message?  

@amarkrsinha1997

**Comment by koushik-nodejs** [comment]
Changes have been made in a course that I am enrolled in.

New Concepts Added
Change in concepts
Don't cover deletion in concepts
A new course has been added. ---

for those above point api is there or we have construct?  -- @amarkrsinha1997

**Comment by amarkrsinha1997** [comment]
> A course I am enrolled in is marked completed. ---
> for this when a course automatically get completed after completing all exercise associated with course then what will be the message?
> 
> @amarkrsinha1997

Automatic completion
Hi, congrats you have completed the course here and now there are more courses have been unlocked.

Manual completion
Hi, congrats you mentor have marked the course as completed which have unlocked few more courses for you which are here below.

**Comment by amarkrsinha1997** [comment]
> Changes have been made in a course that I am enrolled in.
> 
> New Concepts Added
> Change in concepts
> Don't cover deletion in concepts
> A new course has been added. ---
> 
> for those above point api is there or we have construct? -- @amarkrsinha1997

you can find those in seed courses module & they don't require any new api

**Comment by koushik-nodejs** [comment]
> * Hi (student), humne SARAL pe naye courses launch kia inh courses ko niche diye gaye link pe click karke dekh sakte ho.
>   
>   * courseName course url
>   * courseName course url
> 
  As discussed Requirement needs to be updated -- @amarkrsinha1997

**Comment by koushik-nodejs** [comment]
> * Hi (student),
>   
>   * (courseName) course me kuch naye topic add hue hai aap ushe yahan click karke dekh sakte ha.
>     
>     * Exercise Name-Exercise Url
>     * Exercise Name-Exercise Url
>   * Aur kuch purane topics me changes hue hai joh niche diye gaye hai.
>     
>     * Exercise Name Exercise Url
>     * Exercise Name Exercise Url


Need to be discussed -- @amarkrsinha1997

**Comment by amarkrsinha1997** [comment]
> > * Hi (student), humne SARAL pe naye courses launch kia inh courses ko niche diye gaye link pe click karke dekh sakte ho.
> >   
> >   * courseName course url
> >   * courseName course url
> 
> As discussed Requirement needs to be updated -- @amarkrsinha1997
Send 1 course as the message at a time the chances of 2 courses being created simultaneously is very rare so we can proceed with this.

**Comment by amarkrsinha1997** [comment]
> > * Hi (student),
> >   
> >   * (courseName) course me kuch naye topic add hue hai aap ushe yahan click karke dekh sakte ha.
> >     
> >     * Exercise Name-Exercise Url
> >     * Exercise Name-Exercise Url
> >   * Aur kuch purane topics me changes hue hai joh niche diye gaye hai.
> >     
> >     * Exercise Name Exercise Url
> >     * Exercise Name Exercise Url
> 
> Need to be discussed -- @amarkrsinha1997

Can you tell what is needed to be discussed

**Comment by koushik-nodejs** [comment]
> what is needed to be discussed

details flow of it ? can we send the exercise add or update message  in a single message or separately
