### ISSUE TITLE
Support additional profile related information for users

### ISSUE THREAD

**Issue by abhishekgupta92** [navgurukul/galileo#98]
With every user there should be some additional profile details that needs to be added:

- Fields
   - [x] Github link.
   - [x] Linkedin link.
   - [x] Upload Pic.
   - [x] Medium link.

- [x] Add Validation to the fields.
- [ ] Validation of Fields.

## API 2
Create an API to get all the profile information
- Todo: 
- [x] Name
- [x] Email
- [x] Center
- [x] Github Profile Link
- [x] Linkedin Profile Link
- [x] Profile Picture
- [x] Medium Profile Link

**Comment by amarkrsinha1997** [comment]
- Pic will be uploaded as the raw data format(JSON).
- Pic will be uploaded to AWS with absolute URL use aws-sdk that gets key from .aws folder(code is in seed-courses module).

**Comment by koushik-nodejs** [comment]
@amarkrsinha1997  : is asking for link host validation  for the  above update functionality

**Comment by koushik-nodejs** [comment]
@amarkrsinha1997 : is asking for customize error message for link validation

**Comment by koushik-nodejs** [comment]
Done from my end need to review from @amarkrsinha1997

**Comment by amarkrsinha1997** [comment]
Reviewed and Tested
